checkoutLocation: redwood
workspaceLocation: .

tasks:
  - name: redwood
    init: |
      yarn install
      yarn run build:test-project ../redwood-app --typescript
  - name: redwood-app
    command: |
      cd ../redwood-app
