# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
checkoutLocation: redwood
workspaceLocation: .

tasks:
  - name: "Install & Link"
    before: export RW_PATH="/workspace/redwood"
    init: |
      yarn install
      yarn run build:test-project ../redwood-app --typescript --link --verbose
      gp sync-done install-and-link
    command: |
      cd ../redwood-app
      yarn rwt link $RW_PATH
  - name: API
    command: |
      gp sync-await install-and-link
      cd ../redwood-app
      echo "Please wait for 'yarn rwt link' to complete, then run 'yarn rw dev api'"
  - name: WEB
    command: |
      gp sync-await install-and-link
      cd ../redwood-app
      echo "Please wait for 'yarn rwt link' to complete, then run 'yarn rw dev web'"
    openMode: split-right

ports:
  - port: 8911
    onOpen: ignore
  - port: 8910
    onOpen: open-preview
