name: "💬 RFC"
description: "Want feedback on a detailed writeup"

title: "[Feature request]: "

body:
  - type: textarea
    attributes:
      label: Summary
      description: >
    validations:
      required: true

  - type: textarea
    attributes:
      label: Basic example
      description: >

  - type: textarea
    attributes:
      label: Motivation
      description: >
    validations:
      required: true

  - type: Detailed design
    attributes:
      label: Unresolved
      description: >
    validations:
      required: true

  - type: textarea
    attributes:
      label: Unresolved
      description: >

  - type: checkboxes
    attributes:
      label: Are you interested in working on this? (If it applies)
      description: >
        No pressure—this is totally optional!
        We just want to invite you to contribute to Redwood.
        If you choose to contribute, the core team will be there to help you the whole way.


        If this issue is triaged as lower priority,
        your willing and ableness to work on it will land it faster than waiting for a core team member to pick it up.
      options:
        - label: I'm interested in working on this

  - type: markdown
    attributes:
      value: >
        ---

        **About to submit this? Wait!**


        Nice work! 👏 Now that you're all done,
        take a moment to reread your issue's title.
        Is it descriptive enough?
        Does it still ring true? 🤔
        If not, take a moment to rewrite it.
