name: Set up RSC test project
description: Sets up an RSC project for smoke-tests

runs:
  using: node18
  main: 'setUpRscProjectGitHub.mjs'

outputs:
  test-project-path:
    description: Path to the test project
