name: "Change a pull request's milestone"
description: "Change a pull request's milestone"
inputs:
  milestone:
    description: 'milestone'
    required: false
    default: null
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
