# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "Redwood App"
  port = "${WEB_DEV_PORT:8910}"

  # You can customize the GraphQL and dbAuth URLs individually too;
  # see https://redwoodjs.com/docs/app-configuration-redwood-toml#customizing-the-graphql-endpoint.
  apiUrl = "/.redwood/functions"

  includeEnvironmentVariables = [
    # Add any env vars that should be available to the web side to this array;
    # see https://redwoodjs.com/docs/environment-variables#including-environment-variables.
  ]

[api]
  port = "${API_DEV_PORT:8911}"

[browser]
  open = true

[notifications]
  versionUpdates = ["latest"]
