name: Lint, build and run tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  all:
    strategy:
      matrix:
        os: ['windows-latest']
        node-version: ['14']
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} | Node ${{ matrix.node-version }} latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Yarn config # workaround for Windows network timeout
        run: |
          yarn config delete proxy
          npm config rm proxy
          npm config rm https-proxy

      - name: Cache "node_modules"
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules_${{ runner.os }}_${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: BuildJS
        run: yarn build:js
