name: Jest Tests Node 10 and 12

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [dubnium-alpine, erbium-alpine]
    container: node:${{ matrix.node-version }} 

    steps:          
    - run: node --version
    - run: yarn --version
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
      env:
        CI: true
