name: 🚩 Require milestone

on:
  pull_request:
    types: [opened, synchronize, reopened, milestoned, demilestoned]

# Cancel in-progress runs of this workflow.
# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# No top level permissions are required for this workflow
permissions: {}

jobs:
  require-milestone:
    name: 🚩 Require milestone
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: ⬢ Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20

      - name: ✅ Check milestone
        uses: ./.github/actions/require-milestone
